// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRdJ4_9DQFfqaJz0oE7c8bwgCYZ-qT35g',
    appId: '1:102926395042:web:120b59eebc7a9daa9f19fb',
    messagingSenderId: '102926395042',
    projectId: 'myfirebaseproject-c8c85',
    authDomain: 'myfirebaseproject-c8c85.firebaseapp.com',
    storageBucket: 'myfirebaseproject-c8c85.firebasestorage.app',
    measurementId: 'G-HGDDN449F1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwUcRXyn0Fwj2n81r7wxG15g7Bpdv5afc',
    appId: '1:102926395042:android:38514a328bf7e0559f19fb',
    messagingSenderId: '102926395042',
    projectId: 'myfirebaseproject-c8c85',
    storageBucket: 'myfirebaseproject-c8c85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdWYp-lrACEvGS-z-BDArxgrCG_0Z5-s4',
    appId: '1:102926395042:ios:be759091380727ad9f19fb',
    messagingSenderId: '102926395042',
    projectId: 'myfirebaseproject-c8c85',
    storageBucket: 'myfirebaseproject-c8c85.firebasestorage.app',
    iosBundleId: 'com.example.myfirebaseflutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdWYp-lrACEvGS-z-BDArxgrCG_0Z5-s4',
    appId: '1:102926395042:ios:be759091380727ad9f19fb',
    messagingSenderId: '102926395042',
    projectId: 'myfirebaseproject-c8c85',
    storageBucket: 'myfirebaseproject-c8c85.firebasestorage.app',
    iosBundleId: 'com.example.myfirebaseflutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRdJ4_9DQFfqaJz0oE7c8bwgCYZ-qT35g',
    appId: '1:102926395042:web:24bf4173094cb6b59f19fb',
    messagingSenderId: '102926395042',
    projectId: 'myfirebaseproject-c8c85',
    authDomain: 'myfirebaseproject-c8c85.firebaseapp.com',
    storageBucket: 'myfirebaseproject-c8c85.firebasestorage.app',
    measurementId: 'G-3F2733Z2D1',
  );
}
